name: First Workflow 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Silly Message
          run: |
            echo "THIS IS A GITHUB ACTION JOB"
            cat README.md

    job_2:
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10